### ISSUE TITLE
Roadmap - Prototype

### ISSUE THREAD

**Issue by Sheep-y** [Sheep-y/trpg-dnd-5e-pineapple#25]
- [ ] Implement level with mc limit and spell retrain.
- [ ] Re-read the handbook and guide and think hard.
- [ ] Split and redesign model into generic part and system specific part.
- [ ] Experiment with pdf generation.
