### ISSUE TITLE
Roadmap - Alpha

### ISSUE THREAD

**Issue by Sheep-y** [Sheep-y/trpg-dnd-5e-pineapple#26]
- [ ] Design and implement advanced l10n system.
- [ ] Design or find a proper logging system.
- [ ] Refactor or redesign UI to lay the foundation for customisation, advanced navigation, responsive, and touch.
- [ ] System Documentation, core sparrow first then pinbun.
